package com.example.demo.entities;

public enum StatusEntity {
	PENDING, APPROVED, WAITING_FOR_FINANCE_APPROVAL, WAITING_FOR_LAND_VERIFICATION_OFFICE_APPROVAL, REJECTED,
	DOCUMENTS_NOT_UPLOADED, DOCUMENTS_UPLOADED
}
